version: '3'

services:

  fits:
    image: artourkin/fits-web:new_generation
    container_name: fits
    env_file: .env
    networks:
      - web
    restart: unless-stopped
    ports:
      - 8081:8080

  rest:
    image: artourkin/c3po-rest:new_generation
    container_name: rest
    env_file: .env
    networks:
      - web
    restart: unless-stopped
    ports:
      - 8082:8080
    depends_on:
      - fits

  webui:
    image: artourkin/c3po-webui:new_generation
    container_name: webui
    env_file: .env
    networks:
      - web
    restart: unless-stopped
    ports:
      - 8083:8080




networks:
  web: