name: Docker Image CI

on:
  push:
    branches: [ master, new_generation ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and push C3PO REST
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: artourkin/c3po-rest
          dockerfile: ./Dockerfile
          tag_with_ref: true
      - name: Build and push C3PO WEBUI
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: artourkin/c3po-webui
          tag_with_ref: true
          dockerfile: ./webui/Dockerfile
      - name: Build and push FITS WEB
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: artourkin/fits-web
          tag_with_ref: true
          dockerfile: ./fits/Dockerfile